package com.xolo.gzqc.rong;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.


import android.text.TextUtils;

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

/**
 * Entity mapped to table FRIEND.
 */
public class FriendInfo  implements Serializable {

    private static final long serialVersionUID = 8270277246566381723L;
    /**
     * Not-null value.
     */
    @SerializedName("userid")
    private String userId;
    private String name;
    @SerializedName("portraituri")
    private String portraitUri;
    @SerializedName("displayname")
    private String displayName;
    private String status;
    private Long timestamp;
    private String letters;
    /**
     * phone : 13812345698
     * head_portrait :
     * friends_id : 362283B8-1E13-4F97-BCCD-B6C02BBA1689
     */

    private String head_portrait;
    private String friends_id;
    private String phone;

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getLetters() {
        return letters;
    }

    public void setLetters(String letters) {
        this.letters = letters;
    }

    public FriendInfo() {
    }

    public FriendInfo(String userId) {
        this.userId = userId;
    }

    public FriendInfo(String userId, String name, String portraitUri, String displayName) {
        this.userId = userId;
        this.name = name;
        this.portraitUri = portraitUri;
        this.displayName = displayName;
    }


    public FriendInfo(String userId, String name, String portraitUri, String displayName, String letters) {
        this.userId = userId;
        this.name = name;
        this.portraitUri = portraitUri;
        this.displayName = displayName;
        this.letters = letters;
    }

    public FriendInfo(String userId, String name, String portraitUri, String displayName, String status, Long timestamp) {
        this.userId = userId;
        this.name = name;
        this.portraitUri = portraitUri;
        this.displayName = displayName;
        this.status = status;
        this.timestamp = timestamp;
    }

    /**
     * Not-null value.
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPortraitUri() {
        return portraitUri;
    }

    public void setPortraitUri(String portraitUri) {
        this.portraitUri = portraitUri;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    public boolean isExitsDisplayName() {
        if (TextUtils.isEmpty(getDisplayName())) {
            return false;
        }
        return true;
    }

    public String getHead_portrait() {
        return head_portrait;
    }

    public void setHead_portrait(String head_portrait) {
        this.head_portrait = head_portrait;
    }

    public String getFriends_id() {
        return friends_id;
    }

    public void setFriends_id(String friends_id) {
        this.friends_id = friends_id;
    }
}
